### ISSUE TITLE
Add documentation for Form elements

### ISSUE THREAD

**Issue by theOrlin** [telerik/kendo-theme-default#160]
Add documentation for using the form elements in the SASS Default theme. This includes examples with validation.

**Comment by gyoshev** [comment]
The topic is related to the specific framework rather than the theme itself. For reference, this has recently been [added to Kendo UI for Angular](http://www.telerik.com/kendo-angular-ui/components/forms/) docs. If you wish to track such an issue for Kendo UI for jQuery, you can do so via the kendo-ui-core repo.
