### ISSUE TITLE
Kendo Button has additional chrome in IE

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-theme-default#479]
Reported in ticket 1106973. Can be observed in the online demos: http://www.telerik.com/kendo-angular-ui/components/buttons/button/

**Comment by inikolova** [comment]
Related to https://github.com/telerik/kendo-theme-default/issues/196

**Comment by gyoshev** [comment]
The problem is related to the handling of the `background-clip` CSS property in IE. To activate the styles which remove this, use the code below to apply the required classes to the `<html>` element of the page. We will consider implementing this along with the components to reduce the code in your application.

[See this plunker](http://plnkr.co/edit/h1GXgJfxLTvmBYKljHOx?p=preview) for a working demo.

    (function () {
        // 1. detect browser
        var ua = navigator.userAgent;
        var browser = {};
        var browserRxs = {
                edge: /(edge)[ \/]([\w.]+)/i,
                msie: /(msie\s|trident.*? rv:)([\w.]+)/i
            };

        Object.keys(browserRxs).some(function(agent) {
            var match = ua.match(browserRxs[agent]);
            if (match) {
                browser = {};
                browser[agent] = true;
                browser[match[1].toLowerCase().split(" ")[0].split("/")[0]] = true;
                browser.version = parseInt(document.documentMode || match[2], 10);

                return true;
            }
        });

        // 2. add browser-specific CSS class
        var cssClass = "",
            docElement = document.documentElement,
            majorVersion = parseInt(browser.version, 10);

        if (browser.msie) {
            cssClass = "ie";
        } else if (browser.edge) {
            cssClass = "edge";
        }

        if (cssClass) {
            cssClass = "k-" + cssClass + " k-" + cssClass + majorVersion;
        }

        docElement.className += " " + cssClass;
    })();
