### ISSUE TITLE
Grid's layout is broken in RTL mode when all columns have widths

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-theme-default#557]
When all scrollable Grid's columns have explicit widths, and the sum of these widths is less than the width of the viewport, the Grid layout is broken:

[http://plnkr.co/edit/Skhm1hzXAXchgotiZkf5?p=preview](http://plnkr.co/edit/Skhm1hzXAXchgotiZkf5?p=preview)

In the same scenario, not in RTL mode, the available difference between the width of the Grid and the sum of the widths of its columns, is distributed among the columns.

**Comment by inikolova** [comment]
The issue is not related to the theme itself -> there is _inline table width_ applied when Grid is in RTL and all columns have widths. 

Note, a similar inline width is not applied when Grid in LTR mode: 
[http://plnkr.co/edit/PTnVU7IoKAY0g91TXSnv?p=preview](http://plnkr.co/edit/PTnVU7IoKAY0g91TXSnv?p=preview)

I created a new issue in the corresponding repo: 
[https://github.com/telerik/kendo-angular/issues/689](https://github.com/telerik/kendo-angular/issues/689)
