### ISSUE TITLE
PivotGrid rows misaligned

### ISSUE THREAD

**Issue by theOrlin** [telerik/kendo-theme-default#633]
### Description: 
The rows when the inner grid is expanded are not aligned when the text in the cell takes more than one line.

Reproducible by opening http://demos.telerik.com/kendo-ui/pivotgrid/index and expanding All Geographies

Also seen in the screenshot
![](https://cloud.githubusercontent.com/assets/3042944/25624234/7357695c-2f61-11e7-8444-1917bdda7550.png)

Original issue: 1 in https://github.com/telerik/kendo-theme-bootstrap/issues/236

**Comment by MilenaCh** [comment]
It looks ok in Chrome now, but it does not work in the rest of the browsers:

Edge:
https://www.screencast.com/t/ml0z8czEo1NQ
IE:
https://www.screencast.com/t/dSaxDjkmUqp _(Note: the data inside the grid is not visible at all)_ 
Firefox: 
https://www.screencast.com/t/ZZgMmiNj
_Note, the problem is not related to QSF. You can observe exactly the same behavior if isolate the demo from QSF._

**Comment by theOrlin** [comment]
The Pivotgrid in IE is a separate problem, unrelated to the misaligned rows. Split off into a separate issue [here](https://github.com/telerik/kendo-theme-default/issues/647)
