### ISSUE TITLE
Unexpected behavior of disabled buttons

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-theme-default#657]
When Kendo buttons are disabled, the clicks still get propagated to the parent component, which differs from the behavior of a regular disabled button. See [this plunker](http://plnkr.co/edit/6A3Xv8GsoCNINasbrJpv?p=preview).

The issue can be resolved by [overriding the `pointer-events` of disabled buttons](http://plnkr.co/edit/1fHR14hCD43lkLRuPFwI?p=preview)

**Comment by gyoshev** [comment]
This problem occurs due to the use of `pointer-events: none` on disabled elements. Removing it results in more CSS in the theme that is hard to override, so at this point we are reluctant of changing this.

When using event delegation, either check for the disabled state or use the provided style workaround.
