### ISSUE TITLE
Columns are misaligned.

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-theme-default#699]
Grid:

1.Navigate to grid/editing demo.
Result:
https://www.screencast.com/t/W90JrggaY

PivotGrid:
1. Navaigate to pivotgrid/kpi demo.
2. Expand All Geographies and scroll horizontally.

Result:
https://www.screencast.com/t/0vCMxcuu

Valid for SASS themes.

**Comment by theOrlin** [comment]
The problem with the Grid is due to an unexpected behavior of the header table with `width: 100%` when placed inside the `display: flex` header container. The width of the header table is calculated 1px shorter than the width of the content table hence the misalignment.

Adjusting the header scrollbar gap padding with a pixel to compensate for the single pixel misalignment:

- Works for browsers with scrollbar
- Browsers without scrollbar still display the issue
- Causes misalignment in LESS-based themes, which can be fixed but again only for browsers with scrollbar

@joneff

**Comment by theOrlin** [comment]
PivotGrid behavior moved to a separate issue: https://github.com/telerik/kendo-theme-default/issues/817
