### ISSUE TITLE
There are no class names for Grid command buttons

### ISSUE THREAD

**Issue by rusev** [telerik/kendo-theme-default#80]
I'm not able to find class names for Grid command directives. Currently command directives are using the following class names as discussed with @inikolova and @gyoshev :
 - `k-button k-grid-edit-command` for **Edit**
 - `k-button k-grid-save-command` for **Save** (for new/existing items)
 - `k-button k-grid-remove-command` for **Remove**
 - `k-button k-grid-add-command` for **Add new item**

**Comment by gyoshev** [comment]
We can add the following classes to show icons next to the buttons:

```
// Grid commands                                                        
//  uses @extends to allow styling without modifying user content
.k-grid-edit-command,                                                   
.k-grid-save-command,                                                   
.k-grid-remove-command,                                                 
.k-grid-cancel-command,                                                 
.k-grid-add-command {                                                   
    margin: 0 .2em;                                                     

    &::before {                                                         
        @extend .k-icon;                                                

        margin: -2px 4px 0 -4px;                                        
    }                                                                   
}                                                                       

.k-grid-edit-command::before { @extend .k-i-edit; }
.k-grid-save-command::before { @extend .k-i-check; }
.k-grid-remove-command::before { @extend .k-i-close; }
.k-grid-add-command::before { @extend .k-i-add; }
.k-grid-cancel-command::before { @extend .k-i-cancel; }
```

However, I don't like how magical these become. I'd suggest a more explicit way of setting icons, via markup

```
<button kendoGridCancelCommand>
  <span class="k-icon k-i-cancel"></span>
  {{ isNew ? 'Discard' : 'Cancel' }}
</button>
```

This way developers will be able to control which icon they show, and customize the content. Since entering classes manually is error-prone, we can introduce a component or directive for icons (perhaps in a NgModule for styling).

```
<button kendoGridCancelCommand>
  <span kendoIcon [icon]="cancel"></span>
  {{ isNew ? 'Discard' : 'Cancel' }}
</button>
```

What do you think?

**Comment by rkonstantinov** [comment]
I'm OK with requiring an additional element. My only concern is where kendoIcon will live. To me it sounds like its usage is more generic than just the Grid's command column.

**Comment by gyoshev** [comment]
Yes. A `kendo-angular-icons` package, perhaps?

**Comment by gyoshev** [comment]
Alternatively, we could expose the icons from the theme package:

    import { ThemeModule } from "@progress/kendo-theme-default";

Sounds a bit awkward, though.

**Comment by gyoshev** [comment]
After giving it some more thought, exposing the module from the theme package will not allow reuse in the separate component repos (since they don't depend on the theme explicitly). Given that we have [documented the icon class names](http://www.telerik.com/kendo-angular-ui/components/styling/icons/#toc-web-font-icons), an additional icons package seems like an overkill. Since the original issue is fixed, let's consider this matter closed for now.
